package application.api;

import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import application.model.Show;
import application.model.Status;
import application.model.Episode;

public class ShowAPIClient {
	
	/*
	 * The creation of this API Client was guided by the official documentation
	 * of the TMDB API (Source: https://developer.themoviedb.org/docs)
	 */
	
	private static final String BASE_URL = "https://api.themoviedb.org/3";			// baseline of all queries in url form
	private static final String IMAGE_URL = "https://image.tmdb.org/t/p/w500";		// used to get images
	
	// Required attributes for sending and parsing API requests
	private final String accessToken;
	private final HttpClient client;
	private final ObjectMapper mapper;
	
	/**
	 * Creates a ShowAPIClient using the provided TMDB access token.
	 *
	 * @param accessToken the TMDB API access token
	 */
	public ShowAPIClient(String accessToken) {
		this.accessToken = accessToken;
		this.client = HttpClient.newHttpClient();
		this.mapper = new ObjectMapper();
	}
	
	/**
	 * Searches the TMDB API for shows matching the specified query.
	 *
	 * <p>Returned shows are converted into Show objects with default
	 * user-specific values such as status, rating, and review.</p>
	 *
	 * @param query the search term entered by the user
	 * @return a list of matching shows
	 * @throws IOException if an I/O error occurs
	 * @throws InterruptedException if the request is interrupted
	 */
	public List<Show> searchShows(String query) throws IOException, InterruptedException {
		
		// Query is encoded via standard eight-bit character encoding
		String encodedQuery = URLEncoder.encode(query, StandardCharsets.UTF_8);
		
		// Builds TMDB show search URL
		String url = BASE_URL + "/search/tv?query=" + encodedQuery
				   + "&include_adult=false"
				   + "&language=en-US"
				   + "&page=1";
		
		// Sends req and parses the returned JSON
		JsonNode root = sendRequest(url);
		List<Show> shows = new ArrayList<>();
		
		// Retrieves the array containing the search results
		JsonNode results = root.get("results");

		if(results == null || !results.isArray())
			return shows;
		
		// Max limit of 10 results
		int resultCount = Math.min(results.size(), 10);
		
		// Extracts info from each returned show
		for(int i = 0; i < resultCount; i++) {
			JsonNode item = results.get(i);
			int apiId = getIntValue(item, "id");
			
			// Retrieves more detailed information about the show
			JsonNode showDetails = getShowDetails(apiId);

			String title = getTextValue(item, "name");
			String creator = getCreator(showDetails);
			int yearStart = getReleaseYear(showDetails, "first_air_date");
			int yearEnd = getReleaseYear(showDetails, "last_air_date");
			String genre = getGenre(showDetails);
			int numOfSeasons = getIntValue(showDetails, "number_of_seasons");
			boolean airing = getBooleanValue(showDetails, "in_production");
			String imagePath = buildImagePath(getTextValue(item, "poster_path"));
			
			// Retrieves the image paths of all regular seasons
			List<String> seasonImagePaths = getSeasonImagePaths(showDetails);
			
			// Creates the show of each one generated by search
			Show show = new Show(title, creator, yearStart, yearEnd, Status.PLANNED, 0.0, "", genre, numOfSeasons, airing, imagePath);
			
			// Stores the TMDB show ID and image paths
			show.setApiId(apiId);
			show.setSeasonImagePaths(seasonImagePaths);
			shows.add(show);
		}

		return shows;
	}
	
	/**
	 * Retrieves detailed information about a show.
	 *
	 * @param showId the TMDB show ID
	 * @return the parsed JSON response
	 * @throws IOException if an I/O error occurs
	 * @throws InterruptedException if the request is interrupted
	 */
	private JsonNode getShowDetails(int showId) throws IOException, InterruptedException {
		
		// Builds URL for retrieving detailed show information
		String url = BASE_URL + "/tv/" + showId + "?language=en-US";
		return sendRequest(url);
	}
	
	/**
	 * Retrieves detailed information about a season.
	 *
	 * @param showId the TMDB show ID
	 * @param seasonNumber the season number
	 * @return the parsed JSON response
	 * @throws IOException if an I/O error occurs
	 * @throws InterruptedException if the request is interrupted
	 */
	private JsonNode getSeasonDetails(int showId, int seasonNumber) throws IOException, InterruptedException {
		
		// Builds URL for retrieving a specific season and its episodes
		String url = BASE_URL + "/tv/" + showId + "/season/" + seasonNumber + "?language=en-US";
		return sendRequest(url);
	}
	
	/**
	 * Sends an authenticated request to the TMDB API.
	 *
	 * @param url the target TMDB endpoint
	 * @return the parsed JSON response
	 * @throws IOException if an I/O error occurs
	 * @throws InterruptedException if the request is interrupted
	 */
	private JsonNode sendRequest(String url) throws IOException, InterruptedException {
		
		// Creates authenticated GET request for TMDB
		HttpRequest request = HttpRequest.newBuilder()
				.uri(URI.create(url))
				.header("Authorization", "Bearer " + accessToken)
				.header("accept", "application/json")
				.GET()
				.build();
		
		// Sends req and stores returned response
		HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

		if(response.statusCode() != 200)
			throw new IOException("TMDB request failed with status code " + response.statusCode() + ": " + response.body());
		
		// Converts returned JSON text into JsonNode tree
		return mapper.readTree(response.body());
	}
	
	/**
	 * Retrieves all episodes belonging to a season.
	 *
	 * <p>Returned episodes are converted into Episode objects with default
	 * user-specific values such as status, rating, and review.</p>
	 *
	 * @param showApiId the TMDB show ID
	 * @param seasonNumber the season number
	 * @return a list of episodes in the season
	 * @throws IOException if an I/O error occurs
	 * @throws InterruptedException if the request is interrupted
	 */
	public List<Episode> getEpisodes(int showApiId, int seasonNumber) throws IOException, InterruptedException {
		
		JsonNode seasonDetails = getSeasonDetails(showApiId, seasonNumber);
		List<Episode> episodes = new ArrayList<>();
		
		// Retrieves array containing all episodes in the season
		JsonNode results = seasonDetails.get("episodes");

		if(results != null && results.isArray())
		{
			// Extracts info from each ep
			for(JsonNode item : results) {
				int episodeNumber = getIntValue(item, "episode_number");
				String title = getTextValue(item, "name");
				String writer = getEpisodeWriters(item);
				int yearReleased = getReleaseYear(item, "air_date");
				String imagePath = buildImagePath(getTextValue(item, "still_path"));

				Episode episode = new Episode(0, 0, episodeNumber, title, writer, yearReleased, Status.PLANNED, 0.0, "", imagePath);
				episodes.add(episode);
			}
		}

		return episodes;
	}
	
	/**
	 * Retrieves the credited writers of an episode.
	 *
	 * @param episode the JSON object representing an episode
	 * @return the episode writers, or "/--/" if unavailable
	 */
	private String getEpisodeWriters(JsonNode episode) {
		
		// Retrieves episode's crew members
		JsonNode crew = episode.get("crew");
		
		
		// Returns the default value if no crew information is available
		if(crew == null || !crew.isArray())
			return "/--/";

		String writers = "";
		
		// Searches the crew list for writing-related roles
		for(JsonNode crewMember : crew) {
			String job = getTextValue(crewMember, "job");

			if(job.equalsIgnoreCase("Writer") || job.equalsIgnoreCase("Screenplay") || job.equalsIgnoreCase("Teleplay") || job.equalsIgnoreCase("Story")) {
				String name = getTextValue(crewMember, "name");

				if(!name.isBlank() && !writers.contains(name))
				{
					if(!writers.isBlank())
						writers += ", ";

					writers += name;
				}
			}
		}

		if(writers.isBlank())
			return "/--/";

		return writers;
	}
	
	/**
	 * Retrieves the poster image paths of all regular seasons.
	 *
	 * @param showDetails the JSON object representing a show
	 * @return a list of season image paths
	 */
	private List<String> getSeasonImagePaths(JsonNode showDetails) {
		
		// Stores poster path of every regular season
		List<String> seasonImagePaths = new ArrayList<>();
		JsonNode seasons = showDetails.get("seasons");

		if(seasons != null && seasons.isArray())
		{
			for(JsonNode season : seasons) {
				int seasonNumber = getIntValue(season, "season_number");
				
				// Excludes season zero
				if(seasonNumber > 0)
				{
					// Creates empty positions until the correct season index exists
					while(seasonImagePaths.size() < seasonNumber)
						seasonImagePaths.add("");
					
					// Stores season poster
					String posterPath = getTextValue(season, "poster_path");
					seasonImagePaths.set(seasonNumber - 1, buildImagePath(posterPath));
				}
			}
		}

		return seasonImagePaths;
	}
	
	/**
	 * Builds the full TMDB image URL.
	 *
	 * @param filePath the image file path returned by TMDB
	 * @return the complete image URL, or an empty string if unavailable
	 */
	private String buildImagePath(String filePath) {
		
		if(filePath == null || filePath.isBlank())
			return "";
		
		// Combines TMDB image base URL with the returned file path
		return IMAGE_URL + filePath;
	}
	
	/**
	 * Retrieves the show's creators.
	 *
	 * @param node the JSON object representing a show
	 * @return a comma-separated list of creators
	 */
	private String getCreator(JsonNode node) {
		
		// Retrieves the list of show creators
		JsonNode creators = node.get("created_by");

		if(creators == null || !creators.isArray() || creators.isEmpty())
			return "";

		String creator = "";
		
		// Combines all creator names into one comma-separated string
		for(int i = 0; i < creators.size(); i++) {
			if(i > 0)
				creator += ", ";

			creator += getTextValue(creators.get(i), "name");
		}

		return creator;
	}
	
	/**
	 * Retrieves the show's genres.
	 *
	 * @param node the JSON object representing a show
	 * @return a comma-separated list of genres
	 */
	private String getGenre(JsonNode node) {
		
		// Retrieves list of show genres
		JsonNode genres = node.get("genres");

		if(genres == null || !genres.isArray() || genres.isEmpty())
			return "";

		String genre = "";
		
		// Combines all genre names into one comma-separated string
		for(int i = 0; i < genres.size(); i++) {
			if(i > 0)
				genre += ", ";

			genre += getTextValue(genres.get(i), "name");
		}

		return genre;
	}
	
	/**
	 * Retrieves the release year from a date field.
	 *
	 * @param node the parent JSON node
	 * @param fieldName the date field to retrieve
	 * @return the release year, or 0 if unavailable
	 */
	private int getReleaseYear(JsonNode node, String fieldName) {
		
		// Retrieves date string from specified JSON field
		String date = getTextValue(node, fieldName);
		
		if(date.length() < 4)
			return 0;

		try {
			return Integer.parseInt(date.substring(0, 4));
		}
		catch(NumberFormatException e) {
			return 0;
		}
	}
	
	/**
	 * Safely retrieves a text value from a JSON field.
	 *
	 * @param node the parent JSON node
	 * @param fieldName the field to retrieve
	 * @return the field value, or an empty string if unavailable
	 */
	private String getTextValue(JsonNode node, String fieldName) {
		if(node == null)
			return "";

		JsonNode value = node.get(fieldName);
		
		// Returns an empty string if the field is missing or null
		if(value == null || value.isNull())
			return "";

		return value.asText();
	}
	
	/**
	 * Safely retrieves an integer value from a JSON field.
	 *
	 * @param node the parent JSON node
	 * @param fieldName the field to retrieve
	 * @return the field value, or 0 if unavailable
	 */
	private int getIntValue(JsonNode node, String fieldName) {
		if(node == null)
			return 0;

		JsonNode value = node.get(fieldName);
		
		// Returns zero if the field is missing or null
		if(value == null || value.isNull())
			return 0;

		return value.asInt();
	}
	
	/**
	 * Safely retrieves a boolean value from a JSON field.
	 *
	 * @param node the parent JSON node
	 * @param fieldName the field to retrieve
	 * @return the field value, or false if unavailable
	 */
	private boolean getBooleanValue(JsonNode node, String fieldName) {
		if(node == null)
			return false;

		JsonNode value = node.get(fieldName);
		
		// Returns false if the field is missing or null
		if(value == null || value.isNull())
			return false;

		return value.asBoolean();
	}
}